### Problem 1

In [100]:
import numpy as np
import pandas as pd

lst = [10, 20, 30, 40, 50]

arr = np.array(lst)

print(arr)
print(arr.dtype)

data = [
   {'Name': 'Mahfuz Zayn', 'Age': 21, 'City': 'Sylhet'},
   {'Name': 'Omar Faruk Afnan', 'Age': 20, 'City': 'Sylhet'},
   {'Name': 'Afiya Saiyara Anushka', 'Age': 21, 'City': 'Sylhet'},
   {'Name': 'Imeteazul ', 'Age': 21, 'City': 'Sylhet'},
]

df = pd.DataFrame(data)

df

[10 20 30 40 50]
int64

                    Name  Age    City
0            Mahfuz Zayn   21  Sylhet
1       Omar Faruk Afnan   20  Sylhet
2  Afiya Saiyara Anushka   21  Sylhet
3             Imeteazul    21  Sylhet

### Problem 2

In [101]:
df = pd.read_csv("./student_data.csv")

df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     str
 1   FullName              20 non-null     str
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     str
 6   EnrollmentDate        20 non-null     str
 7   Instructor            20 non-null     str
 8   Location              20 non-null     str
dtypes: float64(3), str(6)
memory usage: 1.5 KB

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

### Problem 3

In [102]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

items_df = pd.DataFrame(data)

print(items_df)
print(items_df)
print(items_df.index)
print(items_df['Product'])
items_df.loc[2]

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150
  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150
RangeIndex(start=0, stop=4, step=1)
0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: str

Product     Eraser
Price            5
Quantity       200
Name: 2, dtype: object

### Problem 4

In [103]:
# Using .loc
print(df.loc[1])
print(df.loc[:,'Algorithm Marks'])
print(df.loc[0:1,['Algorithm Marks', 'Python Marks']])

StudentID                      PH1002
FullName                Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  92.0
Python Marks                      NaN
CompletionStatus          In Progress
EnrollmentDate             2024-01-20
Instructor                  Ms. Salma
Location                   Chattogram
Name: 1, dtype: object
0     85.0
1     92.0
2     88.0
3     78.0
4      NaN
5     75.0
6     80.0
7     81.0
8     72.0
9     89.0
10     NaN
11    85.0
12    75.0
13     NaN
14    86.0
15    94.0
16    90.0
17    88.0
18     NaN
19    86.0
Name: Algorithm Marks, dtype: float64
   Algorithm Marks  Python Marks
0             85.0          88.0
1             92.0           NaN

In [104]:
# Using .iloc

df.set_index('StudentID', inplace=True)

df.iloc[1]
df.iloc[3:7]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka

### Problem 5

In [105]:
students_marks = [
    {'Name': 'Mahfuz Zayn', 'Math': 85, 'Science': 90},
    {'Name': 'Omar Faruk', 'Math': 78, 'Science': 88},
    {'Name': 'Afiya Saiyara', 'Math': 92, 'Science': 95},
    {'Name': 'Imteazul Islam', 'Math': 80, 'Science': 85}
]

df = pd.DataFrame(students_marks)

df.drop("Science", axis="columns", inplace=True)
df.drop(3, axis=0, inplace=True)

df

            Name  Math
0    Mahfuz Zayn    85
1     Omar Faruk    78
2  Afiya Saiyara    92

### Problem 6

In [106]:
data = [
    {'Name': 'Mahfuz Zayn', 'Department': 'Software Engineering', 'Salary': 55000},
    {'Name': 'Omar Faruk', 'Department': 'Data Science', 'Salary': 60000},
    {'Name': 'Afiya Saiyara', 'Department': 'Machine Learning', 'Salary': 65000},
    {'Name': 'Imteazul Islam', 'Department': 'Software Engineering', 'Salary': 58000},
    {'Name': 'Fatima Akhter', 'Department': 'Web Development', 'Salary': 52000},
    {'Name': 'Kamal Uddin', 'Department': 'Data Science', 'Salary': 62000},
    {'Name': 'Laila Begum', 'Department': 'DevOps', 'Salary': 59000},
    {'Name': 'Mahmudul Hasan', 'Department': 'Mobile Development', 'Salary': 57000},
    {'Name': 'Sabrina Hossain', 'Department': 'Software Engineering', 'Salary': 56000},
    {'Name': 'Rakib Hasan', 'Department': 'Data Science', 'Salary': 63000},
    {'Name': 'Nusrat Jahan', 'Department': 'Cloud Computing', 'Salary': 61000},
    {'Name': 'Ariful Islam', 'Department': 'UI/UX Design', 'Salary': 54000},
    {'Name': 'Sadia Parvin', 'Department': 'Backend Development', 'Salary': 58000},
    {'Name': 'Tasnim Ayesha', 'Department': 'Frontend Development', 'Salary': 53000},
    {'Name': 'Hasanuzzaman', 'Department': 'DevOps', 'Salary': 59000},
    {'Name': 'Shamsun Nahar', 'Department': 'Data Science', 'Salary': 64000},
    {'Name': 'Fahim Khan', 'Department': 'Machine Learning', 'Salary': 67000},
    {'Name': 'Jannat Ferdous', 'Department': 'Software Engineering', 'Salary': 55000},
    {'Name': 'Rahman Ali', 'Department': 'Database Administration', 'Salary': 57000},
    {'Name': 'Sujata Roy', 'Department': 'Quality Assurance', 'Salary': 52000}
]

df = pd.DataFrame(data)

In [113]:
df.sort_values(['Salary', 'Name'], ascending=[1, 0])

               Name               Department  Salary
19       Sujata Roy        Quality Assurance   52000
4     Fatima Akhter          Web Development   52000
13    Tasnim Ayesha     Frontend Development   53000
11     Ariful Islam             UI/UX Design   54000
0       Mahfuz Zayn     Software Engineering   55000
17   Jannat Ferdous     Software Engineering   55000
8   Sabrina Hossain     Software Engineering   56000
18       Rahman Ali  Database Administration   57000
7    Mahmudul Hasan       Mobile Development   57000
12     Sadia Parvin      Backend Development   58000
3    Imteazul Islam     Software Engineering   58000
6       Laila Begum                   DevOps   59000
14     Hasanuzzaman                   DevOps   59000
1        Omar Faruk             Data Science   60000
10     Nusrat Jahan          Cloud Computing   61000
5       Kamal Uddin             Data Science   62000
9       Rakib Hasan             Data Science   63000
15    Shamsun Nahar             Data Science   64000
2     Afiya Saiyara         Machine Learning   65000
16       Fahim Khan         Machine Learning   67000

### Problem 7

In [123]:
student_scores = [
    {'Name': 'Mahfuz Zayn', 'Score': 85},
    {'Name': 'Omar Faruk', 'Score': 78},
    {'Name': 'Afiya Saiyara', 'Score': 20},
    {'Name': 'Imteazul Islam', 'Score': 80},
    {'Name': 'Fatima Akhter', 'Score': 88},
    {'Name': 'Kamal Uddin', 'Score': 30},
    {'Name': 'Laila Begum', 'Score': 90},
    {'Name': 'Mahmudul Hasan', 'Score': 82}
]

df = pd.DataFrame(student_scores)

filtered_df = df.loc[df['Score'] > 60]
filtered_df_2 = df.loc[df['Score'] < 40]

print(filtered_df)
print(filtered_df_2)

             Name  Score
0     Mahfuz Zayn     85
1      Omar Faruk     78
3  Imteazul Islam     80
4   Fatima Akhter     88
6     Laila Begum     90
7  Mahmudul Hasan     82
            Name  Score
2  Afiya Saiyara     20
5    Kamal Uddin     30